apiVersion: v1
kind: ConfigMap
metadata:
  name: proxysql-conf
data:
  proxysql.cnf: |
    datadir="/var/lib/proxysql"

    admin_variables=
    {
        admin_credentials="proxysql-admin:{{admin_password}}"
        mysql_ifaces="0.0.0.0:6032"
        refresh_interval=2000
    }

    mysql_variables=
    {
        threads=4
        max_connections=2048
        default_query_delay=0
        default_query_timeout=36000000
        have_compress=true
        poll_timeout=2000
        interfaces="0.0.0.0:6033"
        default_schema="information_schema"
        stacksize=1048576
        server_version="5.5.30"
        connect_timeout_server=3000
        monitor_username="proxysql"
        monitor_password="{{monitor_password}}"
        monitor_history=600000
        monitor_connect_interval=60000
        monitor_ping_interval=10000
        monitor_read_only_interval=1500
        monitor_read_only_timeout=500
        ping_interval_server_msec=120000
        ping_timeout_server=500
        commands_stats=true
        sessions_sort=true
        connect_retries_on_failure=10
        set_query_lock_on_hostgroup=0
    }

    mysql_replication_hostgroups =
    (
      { writer_hostgroup=10, reader_hostgroup=20, comment="MySQL Replication 5.7" }
    )

    mysql_servers =
    (
      { address="127.0.0.1" , port=3316 , hostgroup=10, max_connections=100 },
      { address="127.0.0.1" , port=3326 , hostgroup=20, max_connections=100 },
    )

    mysql_users =
    (
      { username = "{{db_username}}" , password = "{{db_password}}" , default_hostgroup = 10 , active = 1 }
    )

    mysql_query_rules =
    (
      {
        rule_id=100
        active=1
        match_pattern="^SELECT .* FOR UPDATE"
        destination_hostgroup=10
        apply=1
      },
      {
        rule_id=200
        active=1
        match_pattern="^SELECT .*"
        destination_hostgroup=20
        apply=1
      },
      {
        rule_id=300
        active=1
        match_pattern=".*"
        destination_hostgroup=10
        apply=1
      }
    )